##### how can we capture similarity between two words?
- so wee can make vector and we can do similarity
- issue with word2vec -Fixed embeddings
     1. he didn't receive fair treatment
     2. Fun fair in new york city this summer
here fun meaning is different but wordembedding will fiixed
#####  to overcome this issue 
#Bert can generate contextualized embeding
#Bert can generate embedding for entire sentence=>all sentence will have only one vector
#### There are two version of Bert
1. Bert Base-->comparable in size to the openai transformer in order to compare performance.12encoded layer
2. Bert Large-->A ridiculously huge model which achieved the state of the art results reported in the paper.24 encoded layer

- bert  is trained on 2500 million words of wikipidia and 800m words of other books
  - How was it trained
    - Massed Language model
    - Next sentance prediction
- google search is powered by bert
- bert full form-->bidirectional encoder representation from transformers



In [ ]:
# !pip install --upgrade tensorflow
!pip install tensorflow_text
# !pip install --upgrade protobuf
import tensorflow_hub as hub
import tensorflow_text as text
#TensorFlow Text is a powerful library that can be used for a variety of text processing tasks.

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 37.0 MB/s eta 0:00:00


In [ ]:
preprocessing_url=("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
#above URL that points to a tensorflow hub module that can be used to preprocess text for use with bert model
encoder_url='https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'


In [ ]:
#to create hub layer and pass your preprocess url
bert_preprocess_model=hub.KerasLayer(preprocessing_url)
#it creates a tensorflow hub layer that can be used to preprocess text data for use with bert model.

In [ ]:
text_test=['nice movie indeed','I love python programing']
text_preprocess=bert_preprocess_model(text_test)
text_preprocess.keys()
#here input_word_ids: A tensor that contain the input text data after it has been tokenized and convertrd to integer ids.
#input_mask:A tensor that indicates which tokens in the input text are padding tookens
#input_type_ids:A tensor that indicates the paer of speech tag for eacch token iin the input text



dict_keys(['input_word_ids', 'input_type_ids', 'input_mask'])

In [ ]:
text_preprocess['input_mask']


<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [ ]:
# we can see that first sentance is having 3 words and mask is 05 
#cls nice movie indeed sep
#so it print cls in begbbning and sep in last thay

In [ ]:
text_preprocess['input_word_ids']
# cls nice movie indeed SEP
#cls is always fixed 101 ans seperation 102

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [ ]:
bert_model=hub.KerasLayer(encoder_url)
bert_results=bert_model(text_preprocess)
bert_results.keys()
#it gives output as dict_keys(['default', 'pooled_output', 'encoder_outputs', 'sequence_output'])
# The Default key contains a tensor that represents the output of the bert model.This tensor can be used for a verity of tasks,such as text classification,sentiment analysis,and question answerig
#The pooled_output key contains a tensor that represents the pooled output of the bert model.The pooled output is a single vector that represent the entire text. This vector can be used fot tasjs that require a global representation of the input text,such as text summarization and question answering.

#Encoder_ouptput key contains a tensor that represents the encoder outputs of the bert model.
#The encoder outputs are sequence of vector that represent the input text at different levels of granularity.
#These vectors can be used for tasks that require a more detailed understanding of the input text, such as named entity recognition and nlp inference


#Sequence_output
#sequence_output key contains a tensor that represent the sequencce output of the BERT model.The Sequence output is a sequence of vectors that represent the input text at the word level.
#These vectors can be used for tasks that require afine grained understanding of the input text,such as part-of-speech tagging and semantic role labeling



dict_keys(['default', 'pooled_output', 'encoder_outputs', 'sequence_output'])

In [ ]:
bert_results['pooled_output']#the embedding vector size is 768

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.791774  , -0.21411902,  0.49769545, ...,  0.24465242,
        -0.47334465,  0.8175868 ],
       [-0.8998869 , -0.5022243 , -0.80149144, ..., -0.602643  ,
        -0.69911593,  0.9073097 ]], dtype=float32)>

In [ ]:
#individual word embeddinng vector
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292041,  0.08567816,  0.14476837, ..., -0.0967708 ,
          0.08722115,  0.07711103],
        [ 0.17839377, -0.19006082,  0.50349444, ..., -0.05869827,
          0.32717147, -0.15578502],
        [ 0.18701456, -0.4338877 , -0.48875162, ..., -0.1550281 ,
          0.00145131, -0.24470958],
        ...,
        [ 0.12083077,  0.12884237,  0.46453524, ...,  0.07375517,
          0.17441934,  0.16522089],
        [ 0.07967839, -0.01190699,  0.5022542 , ...,  0.13777757,
          0.21002182,  0.0062461 ],
        [-0.07212706, -0.2830349 ,  0.5903332 , ...,  0.47551912,
          0.1666846 , -0.08920319]],

       [[ 0.04060526,  0.32671487, -0.06604554, ..., -0.11767737,
          0.20420273,  0.6038268 ],
        [ 0.42078924,  0.38885808, -0.19671586, ..., -0.25060526,
          0.29196504,  0.34592384],
        [ 1.0496668 ,  1.0857546 ,  0.4954928 , ...,  0.31622717,
          0.27401122,  0.26547572],
        ...,