In [1]:
#how can i build my own ner
#approch 1:Simple Lookup you have a database of comany and if add new entity than you manually add that entity
#Rule based NER,in which we are using a specific rule using regular expression
#approch 3:machine learning CRF(conditional Random Fields),Bert



#feature enginearing is a process of extracting the feature of the raw data
#in nlp it is also called text representation
#representing text as a vector is also called as vector space model.
#there are various approches of converting text into vector
#OneHotEncoding,BagofWords,RF-IDF,Word EMbedding


In [2]:
#the disadvantage of label encoding is similar words do not have similar representation
#means take example of assistance andd help both word are similar but the reperesentation of the both the words are different
#it consumes lot of memory and resource 
#out of vocabulary problem
#no fixed length representation #take example I need banna and I need banana shake so,first sentance vector size will be 3000 and second sentance vector size is 4000


In [3]:
#bag of words
#take example if you are doing the news classification and you are writing the python script for web scrapting and from that you want to mention company namem from that article so you can do classification 

#step1 email
#we will take the email body take example as urgent Business assistance. There is 55 millionn $ in your account, claim it hurry up

#step 2 using bag of word we will convert that email into the vector like[3,0,1,0,0,0,6,........,0]

#step 3
#then we will apply naive bayes classifier that will detect the email is spam or not
#Raw text---->Number vector --->Machine learning 




#so, first we will build a vocablary of email
#limitation of bag of words
#it may consume too much memory&compute resources  the memory or resources consumes is less than label encoding
#doent capture meaning of words properly

    

In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
df.Category.value_counts()#in pandas there are function called value count that will count the values

ham     4825
spam     747
Name: Category, dtype: int64

In [7]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [8]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2,random_state=10)

In [10]:
X_train.shape

(4457,)

In [11]:
X_test.shape

(1115,)

In [12]:
type(X_train)

pandas.core.series.Series

In [13]:
X_train[:4]

5281               And how you will do that, princess? :)
1300    Great to hear you are settling well. So what's...
5128    Wot about on wed nite I am 3 then but only til 9!
1808      Do have a nice day today. I love you so dearly.
Name: Message, dtype: object

In [14]:
y_train[:4]

5281    0
1300    0
5128    0
1808    0
Name: spam, dtype: int64

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()

In [16]:
X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7723 sparse matrix of type '<class 'numpy.int64'>'
	with 59346 stored elements in Compressed Sparse Row format>

In [17]:
#so it is sparse matrix and you want to view that matrix than convert that matrix into numpy array
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [18]:
X_train_cv.shape

(4457, 7723)

In [19]:
v.get_feature_names_out()[1000:1050] #it have all the words in the vocablury

array(['appear', 'appendix', 'applausestore', 'applebees', 'apples',
       'application', 'apply', 'applyed', 'applying', 'appointment',
       'appointments', 'appreciate', 'appreciated', 'approaching',
       'appropriate', 'approve', 'approved', 'approx', 'apps', 'appt',
       'appy', 'april', 'aproach', 'apt', 'aquarius', 'ar', 'arab',
       'arabian', 'arcade', 'archive', 'ard', 'are', 'area', 'aren',
       'arent', 'arestaurant', 'aretaking', 'areyouunique', 'argh',
       'argue', 'arguing', 'argument', 'arguments', 'aries', 'arise',
       'arises', 'arm', 'armand', 'armenia', 'arms'], dtype=object)

In [20]:
v.get_feature_names_out().shape

(7723,)

In [21]:
dir(v)#if i want to find the method in this countvectorization than just write dir(vector for you want method)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',

In [22]:
v.vocabulary_

{'and': 938,
 'how': 3507,
 'you': 7684,
 'will': 7497,
 'do': 2346,
 'that': 6782,
 'princess': 5396,
 'great': 3217,
 'to': 6907,
 'hear': 3363,
 'are': 1031,
 'settling': 6018,
 'well': 7434,
 'so': 6261,
 'what': 7454,
 'happenin': 3314,
 'wit': 7524,
 'ola': 4906,
 'wot': 7585,
 'about': 739,
 'on': 4915,
 'wed': 7409,
 'nite': 4768,
 'am': 913,
 'then': 6799,
 'but': 1555,
 'only': 4926,
 'til': 6873,
 'have': 3341,
 'nice': 4749,
 'day': 2156,
 'today': 6913,
 'love': 4208,
 'dearly': 2169,
 'talk': 6674,
 'sexy': 6024,
 'make': 4303,
 'new': 4738,
 'friends': 2992,
 'or': 4956,
 'fall': 2752,
 'in': 3628,
 'the': 6786,
 'worlds': 7576,
 'most': 4568,
 'discreet': 2322,
 'text': 6758,
 'dating': 2153,
 'service': 6009,
 'just': 3853,
 'vip': 7277,
 '83110': 644,
 'see': 5960,
 'who': 7473,
 'could': 2004,
 'meet': 4400,
 'with': 7525,
 'money': 4543,
 'as': 1068,
 'aint': 862,
 'thing': 6814,
 'sha': 6029,
 'if': 3584,
 'still': 6463,
 'havent': 3344,
 'collected': 1866,
 'dough

In [23]:
X_train_np=X_train_cv.toarray()
X_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
np.where(X_train_np[0]!=0)

(array([ 938, 2346, 3507, 5396, 6782, 7497, 7684], dtype=int64),)

In [25]:
X_train[:12][5281]

'And how you will do that, princess? :)'

In [26]:
X_train_np[0][7684]

1

In [27]:
#now step 4 machine learning model
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [28]:
#now i want to evaluate the performance of the model using the countvectoru=ization we will transform x_test because x_test is just email
X_test_cv=v.transform(X_test)
X_test_cv

<1115x7723 sparse matrix of type '<class 'numpy.int64'>'
	with 13664 stored elements in Compressed Sparse Row format>

In [29]:

from sklearn.metrics import classification_report
y_pred=model.predict(X_test_cv)
classification_report=(y_test,y_pred)
#first give the truth that is y_test and then give prediction



In [30]:
emails=[
    'Hey mohan can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for  you. Dont miss this reward!'
]
emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [31]:
#we will do same by sklearn pipeline
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [32]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [33]:
emails=[
    'Hey mohan can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for  you. Dont miss this reward!'
]

clf.predict(emails)
y=clf.predict(X_test)


In [34]:
classification_report(y_test,y)

TypeError: 'tuple' object is not callable